Tugbanur - Week2 assignments
HackYourAssignment/assignments-cohort49 pull request #10
Opened 2024-07-12 14:59 UTC by Tugbanur-f

2024-07-24 21:58 UTC, keremilhan requested changes

2024-07-24 21:58 UTC, keremilhan commented on 1-JavaScript/Week2/assignment/ex3-tellFortune.js
> +
- You can directly return the following code inside this function.
`return array[Math.floor(Math.random() * array.length)];`

2024-07-24 21:58 UTC, keremilhan commented on 1-JavaScript/Week2/assignment/ex5-shoppingCartPure.js
> +  const newShoppingCart = [...array, item];
- You can make your function cleaner by using slice method.
`  return [...shoppingCart, groceryItem].slice(-3);
`

2024-07-24 21:58 UTC, keremilhan commented on 1-JavaScript/Week2/assignment/ex7-mindPrivacy.js
> +  const filteredEmployees =[];
- Use object destructuring to extract the non-private properties. It would be so much easier and cleaner.

2024-07-25 09:23 UTC, Tugbanur-f commented on 1-JavaScript/Week2/assignment/ex5-shoppingCartPure.js
> +  const newShoppingCart = [...array, item];
The topic for Array methods we start in week3. I didn't know about slice methods that's
 why I didn't use it on my assignment. Yes you are right it makes more cleaner.

2024-07-25 09:25 UTC, Tugbanur-f commented on 1-JavaScript/Week2/assignment/ex7-mindPrivacy.js
> +  const filteredEmployees =[];
In week2 I didn't know about array methods. I used what I learn from week1 and week2. Should I change them ?

2024-07-25 10:06 UTC, keremilhan commented on 1-JavaScript/Week2/assignment/ex7-mindPrivacy.js
> +  const filteredEmployees =[];
In the assignment instructions, it says you should use destructring. So, change it if possible.

2024-07-27 09:28 UTC, Tugbanur-f reviewed
I have changed them all.

2024-07-29 09:11 UTC, keremilhan approved these changes

2024-08-10 20:40 UTC, closed without merging